name: upload_artifact

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "navigator.json"

jobs:
  upload_artifact:
    name: Bupload_artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Read Plugin Version
        id: update_data
        run: |
          version=$(jq -r '.Version' navigator.json)
          echo version=$version
          echo "VERSION=$version" >> $GITHUB_ENV
          changelog=$(cat changelog_latest.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT 
          echo "$changelog" >> $GITHUB_OUTPUT 
          echo "EOF" >> $GITHUB_OUTPUT

          git clone https://github.com/45Drives/cockpit-navigator.git
          mkdir navigator artifacts
          cp -r cockpit-navigator/navigator/* navigator
          cp -r docs navigator
          cp CONTRIBUTING.md navigator
          cp CHANGELOG.md navigator
          cp LICENSE.md navigator
          cp navigator.json navigator
          zip -r navigator-$version.zip navigator
          cp navigator-$version.zip artifacts
          cp navigator.json artifacts
          cp artifacts/navigator-$version.zip artifacts/navigator-latest.zip

      - name: Upload To Azure Blob
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_ARTIFACT }}
          container_name: dev
          source_folder: artifacts/
          destination_folder: ./websoft9/plugin/navigator
          delete_if_exists: true
          fail_if_source_empty: true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: /*
          tag_name: v${{ env.VERSION }}-dev
          title: Release-v${{ env.VERSION }}-dev
          body: ${{ steps.update_data.outputs.CHANGELOG }}
          draft: false
          prerelease: true
