name: upload_artifact

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "navigator.json"

jobs:
  upload_artifact:
    name: Bupload_artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Read Plugin Version
        id: update_data
        run: |
          version=$(jq -r '.Version' navigator.json)
          echo version=$version
          real_version=${version%%-*}
          echo "VERSION=$real_version" >> $GITHUB_ENV
          echo "RC_VERSION=$version" >> $GITHUB_ENV
          changelog=$(cat changelog_latest.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT 
          echo "$changelog" >> $GITHUB_OUTPUT 
          echo "EOF" >> $GITHUB_OUTPUT
          if [[ $version == *-* ]]; then
            echo "release version"
            echo "::set-output name=release::false"
          else
            echo "rc release version"
            echo "::set-output name=release::true"
          fi
          git clone https://github.com/45Drives/cockpit-navigator.git
          mkdir navigator artifacts
          cp -r cockpit-navigator/navigator/* navigator
          cp -r docs navigator
          cp CONTRIBUTING.md navigator
          cp CHANGELOG.md navigator
          cp LICENSE.md navigator
          cp navigator.json navigator
          zip -r navigator-$real_version.zip navigator
          cp navigator-$real_version.zip artifacts
          cp navigator.json artifacts
          cp artifacts/navigator-$real_version.zip artifacts/navigator-latest.zip

      - name: Upload To Azure Blob
        if: ${{ steps.update_data.outputs.release == 'false' }}
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_ARTIFACT }}
          container_name: dev
          source_folder: artifacts/
          destination_folder: ./websoft9/plugin/navigator
          delete_if_exists: true
          fail_if_source_empty: true

      - name: Create Release
        if: ${{ steps.update_data.outputs.release == 'false' }}
        uses: softprops/action-gh-release@v1
        with:
          files: /*
          tag_name: ${{ env.RC_VERSION }}
          title: Release-${{ env.RC_VERSION }}
          body: ${{ steps.update_data.outputs.CHANGELOG }}
          draft: false
          prerelease: false

      - name: Upload To Azure Blob
        if: ${{ steps.update_data.outputs.release == 'true' }}
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_ARTIFACT }}
          container_name: release
          source_folder: artifacts/
          destination_folder: ./websoft9/plugin/navigator
          delete_if_exists: true
          fail_if_source_empty: true

      - name: Create Release
        if: ${{ steps.update_data.outputs.release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          files: /*
          tag_name: ${{ env.VERSION }}
          title: Release-${{ env.VERSION }}
          body: ${{ steps.update_data.outputs.CHANGELOG }}
          draft: false
          prerelease: false